aitc_service/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),

    path('', views.home, name='home'),
    path('accounts/', include('accounts.urls')),
    path('pelayanan/', include('pelayanan.urls')),
    path('kategori/', include('master.urls')),

    path('user/', views.userPage, name='user-page'),
]

master/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', kategori, name='kategori'),
    path('editkategori/<str:pk>/', views.editkategori, name='editkategori'),
    path('kategori/kategoridel/<str:pk>/', views.kategoridel, name='kategoridel'),
]

pelayanan/urls.py
from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('', pelayanan, name='pelayanan'),
    path('pengaduan-selesai', views.pengsel, name="pengsel"),
    path('pelayanan/update', views.updateStatus, name="updatestatus"),
    path('pelayanan/filter/', views.filterpelayanan, name='filterpelayanan'),
    path('editstatus/<str:pk>/', views.editstatus, name='editstatus'),
    path('detailpelayanan/<str:pk>/', views.detailpelayanan, name='detailpelayanan'),
    path('detaildaftar/<str:pk>/', views.detaildaftar, name='detaildaftar'),
    path('<str:pk>/delete', views.deletepelayanan, name='deletepelayanan'),
    # path('pelayanan/pelayanandel/<str:pk>/', views.pelayanandel, name='pelayanandel'),
    path('post/<str:pk>', views.respon, name="respon"),
    path('kirimpesan', views.sendchat, name="kirimpesan"),
    path('ajax/getpesan', views.getchat, name="getpesan"),
]

pelayanan/models.py
from django.db import models
from master.models import *
from accounts.models import *
from django.contrib.auth.models import User

# Create your models here.

class Chat(models.Model):
    pengaduan = models.ForeignKey('Pengaduans', null=True, on_delete=models.SET_NULL)
    sender = models.CharField(max_length=255 ,null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False, null=False)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.text

class Pengaduans(models.Model):
    client = models.ForeignKey(Client, null=True, on_delete=models.SET_NULL)
    kategori_pengaduan = models.ForeignKey(KategoriPengaduan, null=True, on_delete=models.SET_NULL)
    keluhan = models.TextField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    selesai = models.BooleanField(null=True)
    kategori_penanganan = models.ForeignKey(KategoriPenanganan, null=True, on_delete=models.SET_NULL)
    respon = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.keluhan

class Respons(models.Model):
    pengaduan = models.ForeignKey(Pengaduans, null=True, on_delete=models.SET_NULL)
    jawab = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

pelayanan/forms.py
from django.forms import ModelForm
from django import forms
from .models import *

class PelayananForm(ModelForm):
    class Meta:
        model = Pengaduans
        fields = '__all__'

class ChatForm(ModelForm):
    class Meta:
        model = Chat
        fields = '__all__'

class DeletePelayananForm(ModelForm):
    class Meta:
        model = Pengaduans
        fields = '__all__'

class JawabForm(ModelForm):
    class Meta:
        model = Respons
        fields = '__all__'

class StatusForm(ModelForm):
    class Meta:
        model = Pengaduans
        fields = ['kategori_penanganan']

class EditStatusForm(ModelForm):
	pk = forms.IntegerField()
	class Meta:
		model = Pengaduans
		fields = '__all__'

class FilterForm(forms.Form):
    KATEGORI=(
        ('', '------------'),
        ("TKP", "TKP"),
        ("Online","Online"),
        ("Selesai","Selesai"),
    )
    kategori_penanganan = forms.ChoiceField(choices=KATEGORI, required=False)

pelayanan/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from aitc_service.views import *
from aitc_service.forms import *
from .forms import *
from .models import *
from .filters import *

# Create your views here.
###############Pengaduan########################################################
@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def pelayanan(request):
    pengaduan = Pengaduans.objects.all()
    client = Client.objects.all()
    stat_online = pengaduan.filter(Q(kategori_penanganan=(2)) | Q(kategori_penanganan=(1)))

    myFilter = filterpenanganan(request.GET, queryset=stat_online)
    orders = myFilter.qs

    form = PelayananForm()
    formup = EditStatusForm()
    if request.method == 'POST':
        form = PelayananForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Data Berhasil Ditambahkan')
            return redirect('pelayanan')

    context = {'pengaduan':pengaduan, 'client':client, 'myFilter':myFilter, 'orders':orders, 'act':'pelayanan', 'form':form, 'formup':formup, 'stat_online':stat_online}
    return render(request, 'pelayanan.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def pengsel(request):
    pengaduan = Pengaduans.objects.all()
    client = Client.objects.all()
    selesai = pengaduan.filter(kategori_penanganan=(3))

    context = {'pengaduan':pengaduan, 'client':client, 'act':'pengsel', 'selesai':selesai}
    return render(request, 'pengsel.html', context)

@login_required(login_url='login')
def updateStatus(request):
	formup = EditStatusForm()

	if request.method =='POST':
		formup = EditStatusForm(request.POST)
		if formup.is_valid():
			idk = formup.cleaned_data['pk']
			kategori_penanganan = formup.cleaned_data['kategori_penanganan']

			Pengaduans.objects.filter(id=idk).update(kategori_penanganan=kategori_penanganan)

			return redirect('pelayanan')

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def filterpelayanan(request):
    pelayananfilter = FilterForm()
    if request.method == 'GET':
        pelayananfilter = FilterForm(request.GET)
        if pelayananfilter.is_valid():
            kategori = pelayananfilter.cleaned_data['kategori_penanganan']

            pelayanan = Pengaduans.objects.filter(kategori_penanganan=kategori)

    context = {'pelayananfilter':pelayananfilter, 'kategori':kategori, 'act':'pelayanan'}
    return render(request, 'pelayanan.html', context)


# @login_required(login_url='login')
# @allowed_users(allowed_roles=['admin'])
# def tambahpelayanan(request):
#     form = PelayananForm()
#     if request.method == 'POST':
#         form = PelayananForm(request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Data Berhasil Ditambahkan')
#             return redirect('pelayanan')
#
#     context = {'form':form, 'act':'pelayanan'}
#     return render(request, 'tambah_pelayanan.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def editstatus(request, pk):
    pengaduan = Pengaduans.objects.get(id=pk)
    form = StatusForm(instance=pengaduan)
    if request.method == 'POST':
        form = StatusForm(request.POST, instance=pengaduan)
        if form.is_valid():
            form.save()
            messages.success(request, 'Data Berhasil Diubah')
            return redirect('pelayanan')

    context = {'form':form, 'pengaduan':pengaduan, 'act':'pelayanan'}
    return render(request, 'edit_status.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def detailpelayanan(request, pk):
    pengaduan = Pengaduans.objects.get(id=pk)
    chatdata = Chat.objects.filter(pengaduan=pk)
    # respon = Respons.objects.get(id=pk)
    form = PelayananForm(instance=pengaduan)
    formchat = ChatForm(initial={'pengaduan':pengaduan, 'sender':request.user})

    if request.method == 'POST':
        form = PelayananForm(request.POST, instance=pengaduan)
        if form.is_valid():
            form.save()
            messages.success(request, 'Data Berhasil Diubah')
            return redirect('detailpelayanan')

    context = {'pengaduan':pengaduan, 'form':form, 'act':'pelayanan', 'formchat':formchat, 'chatdata':chatdata}
    return render(request, 'detail_pelayanan.html', context)

def sendchat(request):
    if request.method == 'POST':
        formchat = ChatForm(request.POST)
        if formchat.is_valid():
            formchat.save()
            return JsonResponse({"success":True}, status=200)
        else:
            return JsonResponse({"success":False}, status=400)

def getchat(request):
    if request.is_ajax():
        chatdata = Chat.objects.filter(pengaduan=request.GET.get('pengaduan'))
        context = {'chatdata': chatdata}
        return render(request, 'partialchat.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def respon(request, pk):
	pengaduan = Pengaduans.objects.filter(id=pk)
	pengaduan1 = Pengaduans.objects.get(id=pk)
	pengaduan2 = Pengaduans.objects.all()
	respon = Respons.objects.filter(pengaduan=pk).order_by("-created_at")
	form = JawabForm(initial={'pengaduan':pengaduan1})

	if request.method == 'POST':
        # print('Printing post: ', request.POST)
		formset = JawabForm(request.POST)
		if formset.is_valid():
			formset.save()
			return redirect('pelayanan')

	context = {'pengaduan': pengaduan, 'pengaduan2':pengaduan2, 'act':'pelayanan', 'respon': respon, 'form':form}
	return render(request, 'detail_pelayanan.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def deletepelayanan(request, pk):
    pengaduan = Pengaduans.objects.get(id=pk)
    form = DeletePelayananForm()

    if request.method == 'POST':
        pengaduan.delete()
        messages.success(request, 'Data Berhasil Dihapus')
        return redirect('pelayanan')

# @login_required(login_url='login')
# @allowed_users(allowed_roles=['admin'])
# def pelayanandel(request, pk):
#     pengaduan = Pengaduans.objects.get(id=pk)
#     if request.method == 'POST':
#         pengaduan.delete()
#         messages.success(request, 'Data Berhasil Dihapus')
#         return redirect('pelayanan')
#
#     context = {'item':pengaduan, 'act':'pelayanan'}
#     return render(request, 'del_pelayanan.html', context)

###############Dashboard########################################################
@login_required(login_url='login')
@allowed_users(allowed_roles=['admin'])
def detaildaftar(request, pk):
    pengaduan = Pengaduans.objects.get(id=pk)
    chatdata = Chat.objects.filter(pengaduan=pk)
    # respon = Respons.objects.get(id=pk)
    form = PelayananForm(instance=pengaduan)
    formchat = ChatForm(initial={'pengaduan':pengaduan, 'sender':request.user})

    context = {'form':form, 'pengaduan':pengaduan, 'act':'dashboard', 'formchat':formchat, 'chatdata':chatdata}
    return render(request, 'detail_daftar.html', context)

templates/akun.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<div class="content-wrapper">
    <br>
      <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <h3>Profil Admin</h3>
        <!-- <a class="btn btn-md btn-info" href="{% url 'tambahadmin' %}">Tambah Admin</a> -->
        <a class="btn btn-md btn-info" href="{% url 'ubahpassword' %}">Ubah Password</a>
        <div class="row">
          <div class="col">
            <br>
            <div class="row">
              <div class="col-md">
                <div class="card card-body">
                  <form method="POST" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="input-group mb-2">
                      <label for="keterangan" class="col-sm-2 col-form-label">Nama</label>
                      {{form.nama}}
                    </div>
                    <div class="input-group mb-2">
                      <label for="keterangan" class="col-sm-2 col-form-label">Alamat</label>
                      {{form.alamat}}
                    </div>
                    <div class="input-group mb-2">
                      <label for="keterangan" class="col-sm-2 col-form-label">Kontak</label>
                      {{form.no_hp}}
                    </div>
                    <div class="input-group mb-2">
                      <label for="keterangan" class="col-sm-2 col-form-label">Email</label>
                      {{form.email}}
                    </div>
                    <input class="btn btn-primary" type="submit" name="Update Information" value="Update Information">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section><!-- /.container-fluid -->




        </div>

//Query All input fields
<script>
var select_fields = document.getElementsByTagName('select')

var input_fields = document.getElementsByTagName('input')


for (var field in select_fields){
  select_fields[field].className += ' form-control'
}
for (var field in input_fields){
  input_fields[field].className += ' form-control'
}
</script>

{% endblock %}

templates/daftarclient.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <br>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <h3>Daftar Klien</h3>
        <a class="btn btn-md btn-info" href="{% url 'tambahuser' %}"><i class="fa fa-plus"></i></a>
        <!-- <a class="btn btn-md btn-info" href="{% url 'tambahclient' %}"><i class="fa fa-address-card"></i></a> -->
        <div class="row">
          <div class="col">
            <br>
              <div class="row">
                <div class="col-md">
                  <div class="card card-body">
                    <table class="table table-striped table-bordered" id="tableclient">
                      <thead>
                        <tr class="bg-info text-center">
                          <th class="bg-info" data-colname="tglpengaduan" data-order="desc">Nama Klien</th>
                          <th data-colname="client" data-order="desc">No.Hp</th>
                          <th data-colname="kategori" data-order="desc">Email</th>
                          <th data-colname="kategori" data-order="desc">Instansi</th>
                          <th data-colname="masalah" data-order="desc">Alamat</th>
                          <th>Aksi</th>
                        </tr>
                      </thead>

                      <tbody>
                        {% for client in client %}
                        <tr class="text-center">
                          <td>{{client.nama}}</td>
                          <td>{{client.no_hp}}</td>
                          <td>{{client.email}}</td>
                          <td>{{client.instansi}}</td>
                          <td>{{client.alamat}}</td>
                          <td>
                          <form action="{% url 'deleteclient' client.id %}" method="post">
                          <a class="btn btn-sm btn-info" href="{% url 'detailclient' client.id %}"><i class="fa fa-pencil-alt"></i></a>
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger btn-sm"
                            onclick="return confirm('Yakin ingin menghapus {{client.nama}} dari daftar client?')"><i class="fa fa-trash"></i></button>
                          </form>
                        </td>

                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>

                  </div>
                </div>
              </div>
            </div>

            </div>
          </div>

        </section>
        </div>

<script type="text/javascript">
  document.getElementById('button').addEventListener('click', function(){
    document.querySelector('.bg-modal').style.display = 'flex';
  });

  document.querySelector('.close').addEventListener('click', function(){
    document.querySelector('.bg-modal').style.display = 'none';
  });
</script>

<script type="text/javascript">
    $(document).ready( function () {
      $('#tableclient').DataTable({
        "lengthMenu": [[5, 10, 20, 50, -1], [5, 10, 20, 50, "All"]]
      });
      });
  </script>
{% endblock %}

templates/edit_status.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<div class="content-wrapper">
    <br>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md">
            <h3>Edit Status Penanganan</h3>
            <div class="card card-body">
              <form method="POST" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group row">
                  <label for="keterangan" class="col-sm-2 col-form-label">Status Penanganan</label>
                  <div class="col-sm-10">
                    {{form.kategori_penanganan}}
                  </div>
                </div>
                <br>
                <input class="btn btn-sm btn-info" type="submit" name="Update Status" value="Update Status">
              </form>
            </div>
          </div>
        </div>

        </div>
        </section><!-- /.container-fluid -->
        </div>

//Query All input fields
<script>
var select_fields = document.getElementsByTagName('select')
var input_fields = document.getElementsByTagName('input')

for (var field in select_fields){
  select_fields[field].className += ' form-control'
}
for (var field in input_fields){
  input_fields[field].className += ' form-control'
}
</script>
{% endblock %}

templates/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{message.tags}} m-10 text-center" id="msg" role="alert">
        {{message}}
    </div>
  {% endfor %}
{% endif %}

templates/pelayanan.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <br>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-2">
      		<h1 class="h3 mb-0 text-gray-800">Data Pengaduan</h1>
          <br>
      		<button type="button" data-toggle="modal" data-target="#pelayananModal" class="d-none d-sm-inline-block btn btn-sm btn-info shadow-sm"><i class="fas fa-plus"></i> Tambah Pengaduan</button>
      	</div>
          <br>
        <div class="form-group row">
          <div class="col-auto">
            <form method="get">
              {{myFilter.form}}
              <br><button class="btn btn-primary" type="submit">Search</button>
            </form>
          </div>
        </div>

          <div class="row">
            <div class="col">
              <div class="row">
                <div class="col-md">
                  <div class="card card-body">
                    <table class="table table-striped table-bordered" id="tablepelayanan">
                      <thead>
                        <tr class="bg-info text-center">
                          <th class="bg-info" data-colname="tglpengaduan" data-order="desc">Tgl Pengaduan</th>
                          <th data-colname="client" data-order="desc">Klien</th>
                          <th data-colname="masalah" data-order="desc">Problem</th>
                          <th data-colname="kategori" data-order="desc">Status Penanganan</th>
                          <th>Aksi</th>
                        </tr>
                      </thead>

                      <tbody>
                        {% for pengaduan in orders %}
                        <tr class="text-center">
                          <td>{{pengaduan.date_created|date:'d F Y, H:i e'}}</td>
                          <td>{{pengaduan.client}}</td>
                          <td>{{pengaduan.keluhan}}</td>
                          <td>{{pengaduan.kategori_penanganan}}</td>
                          <td>
                          <!-- <button id="btneditstatus" type="button" data-toggle="modal" data-target="#statusModal" data-id="{{pengaduan.id}}" data-kategori_penanganan="{{pengaduan.kategori_penanganan}}" class="btn btn-info btn-sm mr-2"><i class="fas fa-truck"></i></button> -->
                          <form action="{% url 'deletepelayanan' pengaduan.id %}" method="post">
                          <a class="btn btn-sm btn-success" href="{% url 'editstatus' pengaduan.id %}"><i class="fa fa-pencil-alt"></i></a>
                          <a class="btn btn-sm btn-info" href="{% url 'detailpelayanan' pengaduan.id %}"><i class="fa fa-info"></i></a>
                          {% csrf_token %}
                          <button type="submit" class="btn btn-danger btn-sm"
                          onclick="return confirm('Yakin ingin menghapus keluhan {{pengaduan.keluhan}} dari pengaduan?')"><i class="fa fa-trash"></i></button>
                          </form>

                          </td>
                          <!-- <form action="{% url 'deletepelayanan' pengaduan.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-sm btn-danger">Hapus</button>
                          </form> -->
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div class="modal fade" id="pelayananModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        	  <div class="modal-dialog" role="document">
        	    <div class="modal-content">
        	      <div class="modal-header">
        	        <h5 class="modal-title" id="exampleModalLabel">Tambah Pelayanan</h5>
        	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        	          <span aria-hidden="true">&times;</span>
        	        </button>
        	      </div>
                <div class="modal-body">
                  <form action="" method="post">
        	        	{% csrf_token %}
          			  <div class="form-group">
          			    <label for="exampleInputEmail1">Nama Klien</label>
                    {{form.client}}
          			  </div>
                  <div class="form-group">
          			    <label for="exampleInputPassword1">Kategori Pengaduan</label>
                    {{form.kategori_pengaduan}}
          			  </div>
                  <div class="form-group">
          			    <label for="exampleInputPassword1" class="col-md-5 col-form-label">Keluhan</label>
                    {{form.keluhan}}
          			  </div>
                  <div class="form-group">
          			    <label for="exampleInputPassword1">Status Penanganan</label>
                    {{form.kategori_penanganan}}
          			  </div>
                </div>
                <div class="modal-footer justify-content-between">
                  <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                  <button type="submit" id="btnSave" class="btn btn-success">Tambah Pengaduan</button>
                </div>
                </form>
              </div>
            </div>
          </div>

          <!-- <div class="modal fade" id="statusModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        	  <div class="modal-dialog" role="document">
        	    <div class="modal-content">
        	      <div class="modal-header">
        	        <h5 class="modal-title" id="exampleModalLabel">Edit Status Penanganan</h5>
        	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        	          <span aria-hidden="true">&times;</span>
        	        </button>
        	      </div>
        	      <div class="modal-body">
        	        <form action="{% url 'updatestatus' %}" method="post">
        	        	{% csrf_token %}
                    {{formup.pk.as_hidden}}
        			  <div class="form-group">
        			    <label for="exampleInputEmail1">Status Penanganan</label>
                  {{formup.kategori_penanganan}}
        			  </div>
        	      </div>
        	      <div class="modal-footer">
        	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        	        <button type="submit" class="btn btn-primary">Simpan</button>
        	      </div>
        	      </form>
        	    </div>
        	  </div>
        	</div> -->

        </div>
      </section>
    </div>

<script type="text/javascript">
  $('#statusModal').on('show.bs.modal', function (event){
    console.log('modalopened');
    var button = $(event.relatedTarget);
    var id = button.data('id');
    var kategori_penanganan = button.data('kategori_penanganan');

    var modal = $(this);
    modal.find('#id_kategori_penanganan').val(kategori_penanganan);
    modal.find('#id_pk').val(id);
  })
</script>

<script>
	$(document).ready(function(){
		$('select').select2({
			width: '100%'
		});
	});
</script>

<script>
/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
 */

//Query All input fields
var text_fields = document.getElementsByTagName('textarea')
text_fields[0].placeholder='';


for (var field in text_fields){
  text_fields[field].className += ' form-control'
}
for (var field in input_fields){
  input_fields[field].className += ' form-control'
}
</script>

<script type="text/javascript">
  document.getElementById('button').addEventListener('click', function(){
    document.querySelector('.bg-modal').style.display = 'flex';
  });

  document.querySelector('.close').addEventListener('click', function(){
    document.querySelector('.bg-modal').style.display = 'none';
  });
</script>

<script type="text/javascript">
    $(document).ready( function () {
      $('#tablepelayanan').DataTable({
        "lengthMenu": [[5, 10, 20, 50, -1], [5, 10, 20, 50, "All"]],
        "order": [[0, "asc"]],
      });
    });
  var select_fields = document.getElementsByTagName('select')

  var input_fields = document.getElementsByTagName('input')


  for (var field in select_fields){
    select_fields[field].className += ' form-control'
  }
  for (var field in input_fields){
    input_fields[field].className += ' form-control'
  }
</script>
{% endblock %}

templates/pengsel.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <br>
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="d-sm-flex align-items-center justify-content-between mb-2">
      		<h1 class="h3 mb-0 text-gray-800">Data Pengaduan Selesai</h1>
        </div>
            <div class="row">
              <div class="col">
                <br>
            <!-- <form method="GET" action="{% url 'filterpelayanan' %}">
              {{pelayananfilter.as_p}}
              <button class="btn btn-primary" type="submit">Filter</button>
            </form> -->
              <div class="row">
                <div class="col-md">
                  <div class="card card-body">
                    <table class="table table-striped table-bordered" id="tablepelayanan">
                      <thead>
                        <tr class="bg-info text-center">
                          <th class="bg-info" data-colname="tglpengaduan" data-order="desc">Tgl Pengaduan</th>
                          <th data-colname="client" data-order="desc">Klien</th>
                          <th data-colname="masalah" data-order="desc">Problem</th>
                          <th data-colname="kategori" data-order="desc">Status Penanganan</th>
                          <th>Aksi</th>
                        </tr>
                      </thead>

                      <tbody>
                        {% for pengaduan in selesai %}
                        <tr class="text-center">
                          <td>{{pengaduan.date_created|date:'d F Y, H:i e'}}</td>
                          <td>{{pengaduan.client}}</td>
                          <td>{{pengaduan.keluhan}}</td>
                          <td>{{pengaduan.kategori_penanganan}}</td>
                          <td>
                            <form action="{% url 'deletepelayanan' pengaduan.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger btn-sm"
                            onclick="return confirm('Yakin ingin menghapus keluhan {{pengaduan.keluhan}} dari pengaduan?')"><i class="fa fa-trash"></i></button>
                            </form>
                          </td>
                        </tr>
                        {% endfor %}
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>

        </div>
      </section>
    </div>

<script type="text/javascript">
  $('#statusModal').on('show.bs.modal', function (event){
    console.log('modalopened');
    var button = $(event.relatedTarget);
    var id = button.data('id');
    var kategori_penanganan = button.data('kategori_penanganan');

    var modal = $(this);
    modal.find('#id_kategori_penanganan').val(kategori_penanganan);
    modal.find('#id_pk').val(id);
  })
</script>

<script>
	$(document).ready(function(){
		$('select').select2({
			width: '100%'
		});
	});
</script>

<script>
/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
//We start indexing at one because CSRF_token is considered and input field
 */

//Query All input fields
var text_fields = document.getElementsByTagName('textarea')
text_fields[0].placeholder='';


for (var field in text_fields){
  text_fields[field].className += ' form-control'
}
for (var field in input_fields){
  input_fields[field].className += ' form-control'
}
</script>

<script type="text/javascript">
  document.getElementById('button').addEventListener('click', function(){
    document.querySelector('.bg-modal').style.display = 'flex';
  });

  document.querySelector('.close').addEventListener('click', function(){
    document.querySelector('.bg-modal').style.display = 'none';
  });
</script>

<script type="text/javascript">
    $(document).ready( function () {
      $('#tablepelayanan').DataTable({
        "lengthMenu": [[5, 10, 20, 50, -1], [5, 10, 20, 50, "All"]],
        "order": [[0, "asc"]],
      });
    });
  var select_fields = document.getElementsByTagName('select')

  var input_fields = document.getElementsByTagName('input')


  for (var field in select_fields){
    select_fields[field].className += ' form-control'
  }
  for (var field in input_fields){
    input_fields[field].className += ' form-control'
  }
</script>
{% endblock %}